common: &default_settings
  :access_key_id: <%= API_CONFIG['amazon_access_key'] %>
  :secret_access_key: <%= API_CONFIG['amazon_access_secret'] %>
  :bucket: <%= API_CONFIG['amazon_bucket_name'] %>

production: &production

  :images:
    :attachment:
      :storage: !ruby/symbol s3
      :s3_protocol: :https
      :s3_credentials:
        <<: *default_settings
      :s3_permissions:
        :product: :public_read
      :default_url: '/assets/missing.png'
      :styles:
        :mini: "48x48>"
        :small: "100x100>"
        :product: "240x240>"
        :large: "600x600>"
      :url: ":s3_domain_url"
      :path: "/spree/products/:id/:style/:basename.:extension"
      :default_url: "/spree/products/:id/:style/:basename.:extension"
      :default_style: "product"
  :taxons:
    :attachment:
      :storage: !ruby/symbol s3
      :s3_protocol: :https
      :s3_credentials:
        <<: *default_settings
      :s3_permissions:
        :product: :public_read
      :default_url: '/assets/missing.png'
      :styles:
        :mini: "48x48>"
        :small: "100x100>"
        :product: "240x240>"
        :large: "600x600>"
      :url: ":s3_domain_url"
      :path: "/spree/products/:id/:style/:basename.:extension"
      :default_url: "/spree/products/:id/:style/:basename.:extension"
      :default_style: "product"

development: &development
  :images:
    :attachment:
      :default_url: '/assets/missing.png'
      :styles:
        :mini: "48x48>"
        :small: "100x100>"
        :product: "240x240>"
        :large: "600x600>"
      :url: "/spree/products/:id/:style/:basename.:extension"
      :path: ":rails_root/public/spree/products/:id/:style/:basename.:extension"
      :default_url: ":rails_root/public/spree/products/:id/:style/:basename.:extension"
      :default_style: "product"
  :taxons:
    :attachment:
      :default_url: '/assets/missing.png'
      :styles:
        :mini: "48x48>"
        :small: "100x100>"
        :product: "240x240>"
        :large: "600x600>"
      :url: "/spree/products/:id/:style/:basename.:extension"
      :path: ":rails_root/public/spree/products/:id/:style/:basename.:extension"
      :default_url: ":rails_root/public/spree/products/:id/:style/:basename.:extension"
      :default_style: "product"
